### ISSUE TITLE
can it be used with a laptop thunderbolt 

### ISSUE THREAD

**Issue by rahmanshaber** [antmicro/thunderbolt-pcie-adapter#1]
Hi, thanks for making this unique product. i am bit confused that uplink thing, so 
I was wondering,
1. can it be used to connect a network adapter to it and connect the thunderbolt port coming from the PCB to my laptop, will it work. like eGPU encloser.
2. can it make 12v using that boost converter using the usbPD protocol to power the PCIE card, or i have to provide my own 12v using that molex connector?
3. will this work with thunderbolt 4

**Comment by pgielda** [comment]
1. Yes, eGPU is just a weird name for a box with a PCB that has a thunderbolt chip, a PCIe connector and a PC power supply to power the GPU. We use it internally with Tesla T4 GPUs.
2. There is a built-in 12V converter. I guess the 12V molex is an alternative power supply for more power hungry devices but someone else would have to chime in here to provide more information
3. I assume so, the chip is Thunderbolt 3, but a Thunderbolt 4 laptop should be backwards compatible

Having said that of course this is just an assumption, a particular setup would have to be tested.

**Comment by rahmanshaber** [comment]
Thanks for the reply, I will wait for more info on 12V side. 
What type of thunderbolt devices you guys used this PCB, I mean the host device like laptop. 
what OS you guys used, any chances tested it with Linux?
Planing to build one for myself or you guys have it for sale?

**Comment by pgielda** [comment]
We do not sell it sadly, you would have to manufacture it yourself. We are a Linux company but having said that this hardware is agnostic to the OS. We use it internally on x86 Intel machines but I cannot disclose details.
