### ISSUE TITLE
firmware for adapter

### ISSUE THREAD

**Issue by chaseadam** [antmicro/thunderbolt-pcie-adapter#2]
Do you have any pointers for firmware to load for the thunderbolt controller. Are you using a generic NVM binary and flashing with Linux (I saw they added flashing in "safe mode"). I believe the latest rev is 27 (last I see mentioned for Alpine Ridge).

I was looking to do exactly this, thanks for making it open source! I have some thunderbolt 3 docks on the way to tear down.

**Comment by Hello-FPGA** [comment]
Did you find the pointers? I am also looking to do this.

**Comment by chaseadam** [comment]
take a look at some of the forks of this repo

**Comment by Hello-FPGA** [comment]
> take a look at some of the forks of this repo

can you give me a direct link to the files? I didn't find that, thanks!
